export type ShortcutCallback = (
	e: KeyboardEvent,
) => boolean | void | Promise<boolean> | Promise<void>;

export type ShortcutAction =
	| "toggleSearch"
	| "toggleFindInNote"
	| "toggleNoteBrowser"
	| "toggleSettings"
	| "toggleStatistics"
	| "togglePinnedThreads"
	| "toggleSidebar"
	| "toggleNoteBrowserLayout"
	| "manageTags"
	| "deleteNote"
	| "closePopup"
	| "focusLastLine"
	| "jumpByNumber"
	| "toggleFuzzy"
	| "toggleSearchMode"
	| "navigateYesterday"
	| "navigateLastAvailable"
	| "navigateToday"
	| "toggleThreadOptionsMode"
	| "threadOptionRemove"
	| "threadOptionLinked"
	| "threadOptionCopy"
	| "threadOptionPin"
	| "unpinThread"
	| "toggleBold"
	| "toggleItalic"
	| "toggleStrikethrough"
	| "toggleCode"
	| "toggleBlockquote"
	| "toggleLink"
	| "copySelection";
